#!/usr/bin/env python3
"""Build the Ephesian Tours site.

    python build.py            # validate content/*.yaml, render dist/, regenerate PENDING.md + credits.md
    python build.py --strict   # also fail on warnings (use before switching preview_mode off)

Steps
  1. load every content/*.yaml file and validate it with the pydantic models in models.py
  2. cross-check the files against each other (ids, routes, images, pending questions)
  3. render templates/base.html.j2 with Jinja2 into dist/index.html, copy assets/, add .nojekyll
  4. write PENDING.md (from pending.yaml) and credits.md (from media.yaml)

Any schema or cross-reference error stops the build with a non-zero exit code.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import sys
from collections import Counter, defaultdict
from datetime import date
from pathlib import Path
from typing import Any, Iterator

import yaml
from jinja2 import Environment, FileSystemLoader, StrictUndefined, select_autoescape
from markupsafe import Markup, escape
from pydantic import BaseModel, ValidationError

import models

ROOT = Path(__file__).resolve().parent
CONTENT = ROOT / "content"
TEMPLATES = ROOT / "templates"
ASSETS = ROOT / "assets"
DIST = ROOT / "dist"
IMG_DIR = ASSETS / "img"

GENERATED_NOTE = "<!-- Generated by build.py from content/{src}. Do not edit by hand. -->"


class BuildError(Exception):
    pass


# --- loading ---------------------------------------------------------------


def load_yaml(path: Path) -> Any:
    if not path.exists():
        raise BuildError(f"missing content file: {path.relative_to(ROOT)}")
    try:
        return yaml.safe_load(path.read_text(encoding="utf-8"))
    except yaml.YAMLError as exc:
        raise BuildError(f"{path.relative_to(ROOT)}: invalid YAML\n{exc}") from exc


def load_content() -> dict[str, Any]:
    """Validate every content file and merge their top-level keys into one namespace.

    The namespace is what templates see and what pending.yaml `updates` paths refer to,
    e.g. `journeys.*.from_price`, `booking.payment_methods`, `site.form_endpoint`.
    """
    content: dict[str, Any] = {}
    errors: list[str] = []
    for stem, model in models.CONTENT_FILES.items():
        try:
            parsed = model.model_validate(load_yaml(CONTENT / f"{stem}.yaml"))
        except ValidationError as exc:
            for err in exc.errors():
                loc = ".".join(str(part) for part in err["loc"]) or "(root)"
                errors.append(f"content/{stem}.yaml: {loc}: {err['msg']}")
            continue
        except BuildError as exc:
            errors.append(str(exc))
            continue
        for key in type(parsed).model_fields:
            if key in content:
                errors.append(f"content/{stem}.yaml: top-level key '{key}' is defined twice")
            content[key] = getattr(parsed, key)
    if errors:
        raise BuildError("content validation failed:\n  " + "\n  ".join(errors))
    return content


# --- content paths -----------------------------------------------------------


def walk(node: Any, path: tuple[str, ...] = ()) -> Iterator[tuple[tuple[str, ...], Any]]:
    """Yield (path, node) for every model, list item, and field in the content tree.

    List items are addressed by their `id`, days by their number `n`, anything else by index.
    """
    yield path, node
    if isinstance(node, BaseModel):
        for name in type(node).model_fields:
            yield from walk(getattr(node, name), (*path, name))
    elif isinstance(node, list):
        for i, item in enumerate(node):
            if isinstance(item, models.Day):
                key = str(item.n)
            else:
                key = str(getattr(item, "id", i)) if isinstance(item, BaseModel) else str(i)
            yield from walk(item, (*path, key))


def parse_pattern(pattern: str) -> tuple[str, ...]:
    """'journeys.seven_churches.days[3]' -> ('journeys', 'seven_churches', 'days', '3')"""
    return tuple(seg for seg in re.split(r"[.\[\]]+", pattern) if seg)


def covers(pattern: tuple[str, ...], path: tuple[str, ...]) -> bool:
    """True if `path` is the pattern's node or inside it. '*' matches one segment."""
    return len(path) >= len(pattern) and all(p in ("*", s) for p, s in zip(pattern, path))


def fmt_path(path: tuple[str, ...]) -> str:
    """('journeys', 'catholic', 'days', '2', 'note') -> 'journeys.catholic.days[2].note'"""
    out = ""
    for seg in path:
        out += f"[{seg}]" if seg.isdigit() else (f".{seg}" if out else seg)
    return out


# --- cross-checks --------------------------------------------------------------


def cross_check(c: dict[str, Any]) -> tuple[list[str], dict[str, list[str]]]:
    """Return (warnings, tagged) where tagged maps question id -> content paths it resolves.

    Raises BuildError on broken references.
    """
    errors: list[str] = []
    warnings: list[str] = []

    def unique(kind: str, ids: list[str]) -> set[str]:
        for dup, n in Counter(ids).items():
            if n > 1:
                errors.append(f"duplicate {kind} id '{dup}'")
        return set(ids)

    site_ids = unique("site", [s.id for s in c["sites"]])
    image_ids = unique("image", [i.id for i in c["images"]])
    video_ids = unique("video", [v.id for v in c["videos"]])
    unique("journey", [j.id for j in c["journeys"]])
    unique("faq", [f.id for f in c["faq"]])
    pending = {p.id: p for p in c["pending"]}
    unique("pending", [p.id for p in c["pending"]])

    # images, videos, routes
    image_refs = [("hero.image", c["hero"].image), ("verse.image", c["verse"].image)]
    image_refs += [(f"journeys.{j.id}.image", j.image) for j in c["journeys"]]
    image_refs += [(f"sites.{s.id}.image", s.image) for s in c["sites"] if s.image]
    image_refs += [(f"videos.{v.id}.poster", v.poster) for v in c["videos"]]
    image_refs += [(f"hosts.people.{p.id}.photo", p.photo.value) for p in c["hosts"].people]
    image_refs += [("partner.gallery.photos", i) for i in c["partner"].gallery.photos]
    image_refs += [("partner_reviews.items.image", r.image) for r in c["partner_reviews"].items]
    image_refs += [("packet.partner_photos", i) for i in c["packet"].partner_photos]
    if c["packet"].hagia_sophia_image:
        image_refs.append(("packet.hagia_sophia_image", c["packet"].hagia_sophia_image))
    for where, image_id in image_refs:
        if image_id not in image_ids:
            errors.append(f"{where}: unknown image '{image_id}' (add it to media.yaml)")

    for j in c["journeys"]:
        for stop in j.route:
            if stop.site not in site_ids:
                errors.append(f"journeys.{j.id}.route: unknown site '{stop.site}' (add it to sites.yaml)")
        if j.video and j.video not in video_ids:
            errors.append(f"journeys.{j.id}.video: unknown video '{j.video}' (add it to media.yaml)")

    for s in c["sites"]:
        if s.featured and not s.image:
            errors.append(f"sites.{s.id}: featured site has no image (every site card needs a photo)")
    hotel_cities = {h.city for h in c["hotels"]}
    for j in c["journeys"]:
        for d in j.days:
            if d.overnight and d.overnight not in hotel_cities:
                errors.append(f"journeys.{j.id}.days[{d.n}]: overnight '{d.overnight}' has no entry in sites.yaml hotels")
    # the FAQ quotes "from" prices in prose: keep them in step with the price data
    priced = [j for j in c["journeys"] if j.prices]
    if priced:
        cost = next((q for q in c["faq"] if q.id == "cost"), None)
        lowest = min(j.prices.winter for j in priced)
        seven = next((j for j in priced if j.id == "seven_churches"), None)
        for amount in [lowest] + ([seven.prices.winter] if seven else []):
            if cost and f"${amount:,}" not in cost.answer:
                errors.append(f"faq.cost: should quote ${amount:,} (a current 'from' price); update the answer")
    group_ids = {g.id for g in c["journey_groups"]}
    for j in c["journeys"]:
        if j.group not in group_ids:
            errors.append(f"journeys.{j.id}.group: '{j.group}' is not in journey_groups")

    for img in c["images"]:
        if img.ready:
            for w in img.widths:
                if not (IMG_DIR / f"{img.file}-{w}.webp").exists():
                    errors.append(f"media.yaml: image '{img.id}' is missing assets/img/{img.file}-{w}.webp")
    unsourced = [i.id for i in c["images"] if not i.ready]
    if unsourced:
        warnings.append(f"{len(unsourced)} images not sourced yet (placeholders shown): {', '.join(unsourced)}")

    # provenance <-> pending.yaml
    all_paths = [path for path, _ in walk_root(c)]
    tagged: dict[str, list[str]] = defaultdict(list)
    for path, node in walk_root(c):
        if not isinstance(node, models.Provenance) or not node.resolves_by:
            continue
        where = fmt_path(path)
        item = pending.get(node.resolves_by)
        if item is None:
            errors.append(f"{where}: resolves_by '{node.resolves_by}' is not in pending.yaml")
            continue
        tagged[item.id].append(where + (" (tracked)" if node.status == "tracked" else ""))
        if not any(covers(parse_pattern(p), path) for p in item.updates):
            warnings.append(f"{where}: not listed in {item.id}.updates")
        if node.status != "confirmed" and item.resolved:
            warnings.append(f"{where}: {item.id} has been answered; update the value and mark it confirmed")
        if node.status == "confirmed" and not item.resolved:
            errors.append(f"{where}: marked confirmed but {item.id} has no answer yet (use status: tracked for final wording)")

    for item in c["pending"]:
        for pattern in item.updates:
            if not any(covers(parse_pattern(pattern), path) for path in all_paths):
                errors.append(f"pending.yaml {item.id}: updates path '{pattern}' matches nothing")
        if not item.resolved and not tagged.get(item.id):
            warnings.append(f"pending.yaml {item.id}: open, but no content field references it")

    if errors:
        raise BuildError("cross-check failed:\n  " + "\n  ".join(errors))

    if not c["site"].preview_mode:
        open_samples = [p for qid, paths in tagged.items() if not pending[qid].resolved for p in paths]
        if open_samples:
            warnings.append(
                f"preview_mode is off but {len(open_samples)} fields are still pending/proposed "
                f"(see PENDING.md); they render without a Sample badge"
            )
    return warnings, tagged


def walk_root(c: dict[str, Any]) -> Iterator[tuple[tuple[str, ...], Any]]:
    for key, value in c.items():
        yield from walk(value, (key,))


# --- rendering -------------------------------------------------------------------


def md_inline(text: str) -> Markup:
    """Escape text, then allow [label](https://url) links and **bold**. Paragraphs on blank lines."""
    html = str(escape(text))
    html = re.sub(
        r"\[([^\]]+)\]\((https?://[^)\s]+)\)",
        r'<a href="\2" target="_blank" rel="noopener">\1</a>',
        html,
    )
    html = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", html)
    paragraphs = [p.strip() for p in html.split("\n\n") if p.strip()]
    return Markup("".join(f"<p>{p}</p>" for p in paragraphs))


def us_date(d: date | None) -> str:
    return f"{d:%b} {d.day}, {d.year}" if d else ""


def map_data(c: dict[str, Any]) -> str:
    """Route data for the Leaflet maps, keyed by journey id."""
    sites = {s.id: s for s in c["sites"]}
    data = {
        j.id: [
            {"name": sites[r.site].name, "lat": sites[r.site].lat, "lng": sites[r.site].lng, "by": r.by,
             "stop": sites[r.site].kind == "stop"}
            for r in j.route
        ]
        for j in c["journeys"]
    }
    # "</" would end the <script> block it is embedded in
    return json.dumps(data, ensure_ascii=False, separators=(",", ":")).replace("</", "<\\/")


def jinja_env() -> Environment:
    """Shared by the site and the pastor's packet (scripts/make_packet.py)."""
    env = Environment(
        loader=FileSystemLoader(TEMPLATES),
        undefined=StrictUndefined,
        autoescape=select_autoescape(["html", "j2"]),
        trim_blocks=True,
        lstrip_blocks=True,
    )
    env.filters["md"] = md_inline
    env.filters["us_date"] = us_date
    return env


def template_context(c: dict[str, Any], base_url: str) -> dict[str, Any]:
    return dict(
        c,
        images_by_id={i.id: i for i in c["images"]},
        sites_by_id={s.id: s for s in c["sites"]},
        videos_by_id={v.id: v for v in c["videos"]},
        hotels_by_city={h.city: h for h in c["hotels"]},
        map_data=map_data(c),
        base_url=base_url,
        build_year=date.today().year,
    )


def render(c: dict[str, Any], base_url: str) -> str:
    return jinja_env().get_template("base.html.j2").render(**template_context(c, base_url))


def write_dist(html: str) -> None:
    if DIST.exists():
        shutil.rmtree(DIST)
    DIST.mkdir()
    (DIST / "index.html").write_text(html, encoding="utf-8")
    (DIST / ".nojekyll").touch()  # serve files as-is on GitHub Pages
    if ASSETS.exists():
        shutil.copytree(ASSETS, DIST / "assets", ignore=shutil.ignore_patterns(".DS_Store"))


# --- generated docs --------------------------------------------------------------


def write_pending_md(c: dict[str, Any], tagged: dict[str, list[str]]) -> None:
    items = c["pending"]
    open_items = [p for p in items if not p.resolved]
    n_fields = sum(1 for p in open_items for f in tagged.get(p.id, []) if not f.endswith("(tracked)"))
    lines = [
        GENERATED_NOTE.format(src="pending.yaml"),
        "",
        "# Pending items",
        "",
        f"{len(open_items)} open items · {len(items) - len(open_items)} resolved · "
        f"{n_fields} fields on the site currently show a **Sample** badge in preview mode. "
        "Fields marked (tracked) show final wording without a badge but stay listed here.",
        "",
        "To resolve an item: add `answer` and `answered_on` in `content/pending.yaml`, update the "
        "fields listed under it with real values and `status: confirmed`, then run `python build.py`.",
        "",
    ]

    def block(p: models.PendingItem) -> list[str]:
        box = "x" if p.resolved else " "
        head = f"- [{box}] **{p.id}: {p.topic}**"
        if p.asked_on:
            head += f" (asked {us_date(p.asked_on)})"
        out = [head, f"  - {p.question}"]
        if p.resolved:
            src = f"; source: {p.source}" if p.source else ""
            out.append(f"  - **Answer** ({us_date(p.answered_on)}{src}): {p.answer}")
        out.append("  - Updates: " + ", ".join(f"`{u}`" for u in p.updates))
        fields = tagged.get(p.id, [])
        if fields and not p.resolved:
            out.append(f"  - Fields on the site ({len(fields)}): " + ", ".join(f"`{f}`" for f in fields))
        return out

    groups = [
        ("Awaiting our ground operator", [p for p in open_items if p.owner == "operator"]),
        ("Ephesian Tours to-do", [p for p in open_items if p.owner == "ephesian"]),
        ("Resolved", [p for p in items if p.resolved]),
    ]
    for title, group in groups:
        if group:
            lines += [f"## {title}", ""]
            for p in group:
                lines += block(p)
            lines.append("")
    (ROOT / "PENDING.md").write_text("\n".join(lines), encoding="utf-8")


def write_credits_md(c: dict[str, Any]) -> None:
    lines = [
        GENERATED_NOTE.format(src="media.yaml"),
        "",
        "# Image and video credits",
        "",
        "Every image and video used on the site, with its source and license.",
        "",
        "## Images",
        "",
    ]
    ready = [i for i in c["images"] if i.ready]
    if ready:
        lines += ["| Image | Subject | Author | License | Source |", "|---|---|---|---|---|"]
        for i in ready:
            lic = f"[{i.license}]({i.license_url})" if i.license_url else i.license
            src = (f"[link](<{i.source_url}>)" if i.source_url
                   else "provided by Azim Tours, used with permission" if i.author == "Azim Tours" else "our own photo")
            lines.append(f"| `{i.file}` | {i.subject} | {i.author} | {lic} | {src} |")
    else:
        lines.append("No images sourced yet.")
    pending_imgs = [i for i in c["images"] if not i.ready]
    if pending_imgs:
        lines += ["", "### Not yet sourced (placeholders on the site)", ""]
        lines += [f"- `{i.id}`: {i.subject}" for i in pending_imgs]
    if c["videos"]:
        lines += ["", "## Videos", "", "| Video | Author | License | Source |", "|---|---|---|---|"]
        for v in c["videos"]:
            lines.append(f"| {v.title} | {v.author} | {v.license} | [{v.source_url}](<{v.source_url}>) |")
    lines.append("")
    (ROOT / "credits.md").write_text("\n".join(lines), encoding="utf-8")


# --- main --------------------------------------------------------------------------


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--strict", action="store_true", help="treat warnings as errors")
    parser.add_argument(
        "--base-url",
        default=os.environ.get("SITE_BASE_URL"),
        help="absolute URL the site is served from, for canonical/OG tags "
        "(default: $SITE_BASE_URL, else site.base_url). The deploy workflow passes the Pages URL.",
    )
    parser.add_argument(
        "--packet", action="store_true",
        help="also generate the pastor's info packet PDF into dist/ (needs Playwright + Chromium)",
    )
    args = parser.parse_args()

    try:
        content = load_content()
        warnings, tagged = cross_check(content)
        base_url = (args.base_url or str(content["site"].base_url)).rstrip("/") + "/"
        write_dist(render(content, base_url))
        packet_pdf = DIST / content["contact"].packet_file
        if args.packet:
            sys.path.insert(0, str(ROOT / "scripts"))
            from make_packet import make_packet  # imported lazily: needs Playwright

            pages = make_packet(content, packet_pdf)
            if not packet_pdf.exists() or packet_pdf.stat().st_size < 50_000:
                raise BuildError(f"packet PDF missing or too small: {packet_pdf.relative_to(ROOT)}")
            print(f"built {packet_pdf.relative_to(ROOT)} ({pages} pages, {packet_pdf.stat().st_size // 1024} KB)")
        elif not content["contact"].info_packet.sample:
            warnings.append(
                f"{packet_pdf.name} not generated (run with --packet); the packet download link 404s in this build"
            )
        write_pending_md(content, tagged)
        write_credits_md(content)
    except BuildError as exc:
        print(f"BUILD FAILED: {exc}", file=sys.stderr)
        return 1

    for warning in warnings:
        print(f"warning: {warning}", file=sys.stderr)
    if warnings and args.strict:
        print("BUILD FAILED: warnings with --strict", file=sys.stderr)
        return 1

    mode = "preview" if content["site"].preview_mode else "production"
    print(f"built dist/index.html ({mode} mode), PENDING.md, credits.md")
    return 0


if __name__ == "__main__":
    sys.exit(main())
